# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Native_iOS_App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'React', :podspec => '../../React Native App/Bakesale/node_modules/react-native/React.podspec'
pod 'React-Core', :podspec => '../../React Native App/Bakesale/node_modules/react-native/React-Core.podspec'
pod 'React-CoreModules', :path => '../../React Native App/Bakesale/node_modules/react-native/React/CoreModules'
pod 'React-RCTActionSheet', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/ActionSheetIOS'

pod 'ReactCommon', :path => '../../React Native App/Bakesale/node_modules/react-native/ReactCommon'
pod 'React-RCTAnimation', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/NativeAnimation'
pod 'React-RCTBlob', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/Blob'
pod 'React-RCTImage', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/Image'
pod 'React-RCTLinking', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/LinkingIOS'
pod 'React-RCTNetwork', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/Network'
pod 'React-RCTSettings', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/Settings'
pod 'React-RCTText', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/Text'
pod 'React-RCTVibration', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/Vibration'
pod 'React-cxxreact', :path => '../../React Native App/Bakesale/node_modules/react-native/ReactCommon/cxxreact'
pod 'React-jsi', :path => '../../React Native App/Bakesale/node_modules/react-native/ReactCommon/jsi'
pod 'React-jsiexecutor', :path => '../../React Native App/Bakesale/node_modules/react-native/ReactCommon/jsiexecutor'
pod 'React-jsinspector', :path => '../../React Native App/Bakesale/node_modules/react-native/ReactCommon/jsinspector'
pod 'React-perflogger', :path => '../../React Native App/Bakesale/node_modules/react-native/ReactCommon/reactperflogger'
pod 'FBReactNativeSpec', :path => '../../React Native App/Bakesale/node_modules/react-native/React/FBReactNativeSpec'
pod 'RCTTypeSafety', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/TypeSafety'
pod 'RCTRequired', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/RCTRequired'
pod 'FBLazyVector', :path => '../../React Native App/Bakesale/node_modules/react-native/Libraries/FBLazyVector'
pod 'React-callinvoker', :path => "../../React Native App/Bakesale/node_modules/react-native/ReactCommon/callinvoker"
pod 'React-runtimeexecutor', :path => "../../React Native App/Bakesale/node_modules/react-native/ReactCommon/runtimeexecutor"


# Your 'node_modules' directory is probably in the root of your project,
      # but if not, adjust the `:path` accordingly

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'Yoga', :path => '../../React Native App/Bakesale/node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../../React Native App/Bakesale/node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../../React Native App/Bakesale/node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'RCT-Folly', :podspec => '../../React Native App/Bakesale/node_modules/react-native/third-party-podspecs/RCT-Folly.podspec'

  # Pods for Native_iOS_App

  target 'Native_iOS_AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Native_iOS_AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
